#!/usr/bin/env python3
"""Pack 133 — Device QA Evidence Manifest Builder.

Reads the Pack 133 harness report and any user-provided manual evidence files
in $QA_EVIDENCE_DIR, then writes a sanitized Markdown manifest to
docs/divine/device_qa_evidence_manifest_PACK_133.md.

The builder NEVER writes DB, NEVER persists raw JWT, NEVER stores secrets.
All outputs are sanitized via the same redaction policy as the harness.
"""
from __future__ import annotations
import json, os, sys
from datetime import datetime, timezone
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
HARNESS_REPORT = REPO_ROOT / 'backend' / 'scripts' / 'reports' / 'pack_133_device_qa_evidence_harness_report.json'
MANIFEST_MD = REPO_ROOT / 'docs' / 'divine' / 'device_qa_evidence_manifest_PACK_133.md'
CHAIN_MARKER = REPO_ROOT / 'data' / 'design' / 'system_safety' / 'pack_133_final_pre_qa_chain_marker.json'
EVIDENCE_MARKER = REPO_ROOT / 'data' / 'design' / 'system_safety' / 'pack_133_device_qa_evidence_marker.json'


def _load(path):
    try:
        return json.loads(path.read_text(encoding='utf-8'))
    except Exception:
        return None


def _safe(s, default='—'):
    return s if s else default


def main():
    harness = _load(HARNESS_REPORT) or {}
    chain = _load(CHAIN_MARKER) or {}
    evidence = _load(EVIDENCE_MARKER) or {}

    evidence_dir_env = os.getenv('QA_EVIDENCE_DIR')
    evidence_files = []
    if evidence_dir_env:
        ed = (REPO_ROOT / evidence_dir_env).resolve()
        if ed.exists():
            for f in sorted(ed.glob('**/*')):
                if f.is_file():
                    try:
                        rel = f.relative_to(REPO_ROOT)
                    except ValueError:
                        rel = f
                    evidence_files.append(str(rel))

    lines = []
    lines.append('# Device QA Evidence Manifest — PACK 133 (sanitized)')
    lines.append('')
    lines.append('> Manifest read-only. Generated by `device_qa_evidence_manifest_builder.py`.')
    lines.append('> Never contains raw JWT, raw passwords, or raw secrets. Redaction policy enforced.')
    lines.append('')
    lines.append('## Pack chain status')
    lines.append('')
    lines.append('| Pack | Stato |')
    lines.append('| --- | --- |')
    for k in ['pack_127_status', 'pack_128_status', 'pack_129_status',
              'pack_130_status', 'pack_131_status', 'pack_132_status',
              'pack_133_status']:
        lines.append(f'| {k.replace("_status", "").upper().replace("_", " ")} | `{_safe(chain.get(k))}` |')
    lines.append('')
    lines.append('## Commit / SHA chain')
    lines.append('')
    lines.append(f'- Pack 132 final baseline: `{_safe(chain.get("base_pack_132_final_sha"))}`')
    lines.append(f'- Pack 133 evidence harness commit: see git log (this run)')
    lines.append(f'- Public branch: `{_safe(chain.get("public_branch"))}`')
    lines.append('')
    lines.append('## Device QA gate status')
    lines.append('')
    lines.append(f'- device_qa_status: **`{_safe(chain.get("device_qa_status"))}`**')
    lines.append(f'- release_ready: **`{chain.get("release_ready", False)}`**')
    lines.append(f'- runtime_mutation_scope: **`{_safe(chain.get("runtime_mutation_scope"))}`**')
    lines.append(f'- db_write_scope: **`{_safe(chain.get("db_write_scope"))}`**')
    lines.append(f'- reward_progress_scope: **`{_safe(chain.get("reward_progress_scope"))}`**')
    lines.append('')
    lines.append('## Authenticated smoke status')
    lines.append('')
    lines.append(f'- AUTHENTICATED_SMOKE_STATUS: **`{_safe(harness.get("AUTHENTICATED_SMOKE_STATUS"))}`**')
    lines.append(f'- DEVICE_EVIDENCE_STATUS: **`{_safe(harness.get("DEVICE_EVIDENCE_STATUS"))}`**')
    lines.append(f'- SCREENSHOT_EVIDENCE_STATUS: **`{_safe(harness.get("SCREENSHOT_EVIDENCE_STATUS"))}`**')
    lines.append(f'- MANUAL_SIGNOFF_STATUS: **`{_safe(harness.get("MANUAL_SIGNOFF_STATUS"))}`**')
    lines.append(f'- JWT fingerprint (sha256 12-char, never raw): `{_safe(harness.get("qa_jwt_fingerprint"))}`')
    lines.append('')
    lines.append('## Endpoint evidence summary')
    lines.append('')
    lines.append('### Safe GET endpoints exercised')
    for ep in harness.get('safe_get_endpoints', []) or []:
        lines.append(f'- `{ep}`')
    lines.append('')
    lines.append('### Forbidden endpoints NEVER called')
    for ep in harness.get('forbidden_endpoints_never_called', []) or []:
        lines.append(f'- `{ep}`')
    lines.append('')
    lines.append('### Phase 1 probes (unauth, GET-only)')
    for p in harness.get('phase_1_unauth_probes', []) or []:
        lines.append(f'- `{p.get("endpoint")}` auth=`{p.get("auth")}` code=`{p.get("status_code")}` expected=`{p.get("expected")}` result=`{p.get("result")}`')
    lines.append('')
    lines.append('### Phase 2 probes (auth, GET-only)')
    p2 = harness.get('phase_2_auth_probes', []) or []
    if not p2:
        lines.append('- **NOT_EXECUTED** (MANUAL_REQUIRED — env QA assenti)')
    else:
        for p in p2:
            lines.append(f'- `{p.get("endpoint")}` code=`{p.get("status_code")}` result=`{p.get("result")}`')
    lines.append('')
    lines.append('## Physical device / Expo Go status')
    lines.append('')
    lines.append(f'- platform: `{_safe(harness.get("qa_device_platform"))}`')
    lines.append(f'- label: `{_safe(harness.get("qa_device_label"))}`')
    lines.append(f'- physical_device_status: **`{_safe(evidence.get("physical_device_status"))}`**')
    lines.append('')
    lines.append('## Manual signoff status')
    lines.append('')
    lines.append(f'- manual_signoff_status: **`{_safe(evidence.get("manual_signoff_status"))}`**')
    lines.append('- per il signoff manuale, vedere `docs/divine/device_qa_manual_checklist_PACK_133.md`')
    lines.append('')
    lines.append('## Evidence files registered')
    lines.append('')
    if not evidence_files:
        lines.append('- nessun file di evidence registrato in `$QA_EVIDENCE_DIR` in questo run (MANUAL_REQUIRED).')
    else:
        for f in evidence_files:
            lines.append(f'- `{f}`')
    lines.append('')
    lines.append('## Secret redaction policy')
    lines.append('')
    pol = harness.get('secret_redaction_policy') or {}
    for k, v in (pol.items() if isinstance(pol, dict) else []):
        lines.append(f'- `{k}`: **`{v}`**')
    lines.append('')
    lines.append('## No DB write / no reward mutation confirmation')
    lines.append('')
    lines.append(f'- db_write_scope: **`{_safe(harness.get("db_write_scope"))}`**')
    lines.append(f'- runtime_mutation_scope: **`{_safe(harness.get("runtime_mutation_scope"))}`**')
    lines.append(f'- reward_progress_scope: **`{_safe(harness.get("reward_progress_scope"))}`**')
    lines.append('')
    lines.append('## Known gaps')
    for g in evidence.get('known_gaps', []) or []:
        lines.append(f'- {g}')
    lines.append('')
    lines.append('## Final recommendation')
    lines.append('')
    lines.append('- Verdetto Pack 133: **`PACK_133_DEVICE_QA_EVIDENCE_HARNESS_PARTIAL_EVIDENCE_MANUAL_REQUIRED_REAUDIT_REQUIRED`**')
    lines.append('- Catena Pre-QA 127→133: **`PACK_127_133_CHAIN_COMPLETE_REAUDIT_REQUIRED`**')
    lines.append('- Release ready: **NO** (mai dichiarato).')
    lines.append('')
    lines.append(f'_Generato: {datetime.now(timezone.utc).isoformat()}_')

    MANIFEST_MD.parent.mkdir(parents=True, exist_ok=True)
    MANIFEST_MD.write_text('\n'.join(lines) + '\n', encoding='utf-8')
    print(f'wrote: {MANIFEST_MD.relative_to(REPO_ROOT)}')
    return 0


if __name__ == '__main__':
    sys.exit(main())
