/**
 * RM1.22-D — Placeholder contracts for official 1★/2★ heroes.
 *
 * Generated from data/design/placeholder_assignment_1star_2star_manifest.json.
 *
 * These are placeholder_dev contracts only.
 * They wire local placeholder files that were copied in RM1.22-C.
 *
 * Do not mark these assets as final.
 * Do not activate heroes from this file.
 */

import { ImageSourcePropType } from 'react-native';
import type { HeroAssetContract } from './hopliteAssets';

type PlaceholderAssetMap = {
  transparent: ImageSourcePropType;
  card: ImageSourcePropType;
  detail: ImageSourcePropType;
  combat_base: ImageSourcePropType;
};

export type PlaceholderLabHeroRole =
  | 'Tank'
  | 'DPS Melee'
  | 'DPS Ranged'
  | 'Mage AoE'
  | 'Assassin'
  | 'Support'
  | 'Healer'
  | 'Control'
  | 'Hybrid';

export type PlaceholderLabHeroOption = {
  id: string;
  name: string;
  element: string;
  faction: string;
  rarity: number;
  role: PlaceholderLabHeroRole;
};

const RUNTIME_FRAME_WIDTH = 640;
const RUNTIME_FRAME_HEIGHT = 768;

function makeRuntimeSheet(
  source: ImageSourcePropType,
  frames: number,
  columns: number,
  fps: number,
  loop: boolean,
) {
  return {
    source,
    frames,
    columns,
    rows: 1,
    fps,
    loop,
    frameWidth: RUNTIME_FRAME_WIDTH,
    frameHeight: RUNTIME_FRAME_HEIGHT,
    visualScale: 1.0,
  };
}

export const PLACEHOLDER_HERO_IDS_1STAR_2STAR = [
  'greek_phalanx_recruit',
  'demonic_infernal_handmaiden',
  'egyptian_nile_guard',
  'celtic_forest_archer',
  'norse_rune_initiate',
  'angelic_sanctuary_acolyte',
  'angelic_sacred_novice',
  'yokai_veiled_spirit',
  'egyptian_temple_guardian',
  'norse_valhalla_warden',
  'egyptian_desert_blade',
  'celtic_menhir_warrior',
  'egyptian_oasis_markswoman',
  'yokai_huntress',
  'yokai_thunder_novice',
  'yokai_shinobi_shadow',
  'angelic_cantor',
  'egyptian_nile_healer',
  'cursed_bone_sibyl',
  'demonic_infernal_adept',
] as const;

export const PLACEHOLDER_LAB_HERO_OPTIONS_1STAR_2STAR: PlaceholderLabHeroOption[] = [
  { id: 'greek_phalanx_recruit', name: 'Recluta di Falange', element: 'Terra', faction: 'Greca', rarity: 1, role: 'Tank' },
  { id: 'demonic_infernal_handmaiden', name: 'Ancella Infernale', element: 'Fuoco', faction: 'Demonica', rarity: 1, role: 'DPS Melee' },
  { id: 'egyptian_nile_guard', name: 'Guardia del Nilo', element: 'Acqua', faction: 'Egizia', rarity: 1, role: 'DPS Melee' },
  { id: 'celtic_forest_archer', name: 'Arciera di Bosco', element: 'Vento', faction: 'Celtica', rarity: 1, role: 'DPS Ranged' },
  { id: 'norse_rune_initiate', name: 'Iniziata Runica', element: 'Fulmine', faction: 'Norrena', rarity: 1, role: 'Mage AoE' },
  { id: 'angelic_sanctuary_acolyte', name: 'Accolita del Santuario', element: 'Luce', faction: 'Angelica', rarity: 1, role: 'Support' },
  { id: 'angelic_sacred_novice', name: 'Novizia Sacra', element: 'Luce', faction: 'Angelica', rarity: 1, role: 'Healer' },
  { id: 'yokai_veiled_spirit', name: 'Spirito Velato', element: 'Oscurità', faction: 'Japanese Yokai', rarity: 1, role: 'Control' },
  { id: 'egyptian_temple_guardian', name: 'Guardiana del Tempio', element: 'Terra', faction: 'Egizia', rarity: 2, role: 'Tank' },
  { id: 'norse_valhalla_warden', name: 'Custode del Valhalla', element: 'Vento', faction: 'Norrena', rarity: 2, role: 'Tank' },
  { id: 'egyptian_desert_blade', name: 'Lama del Deserto', element: 'Fuoco', faction: 'Egizia', rarity: 2, role: 'DPS Melee' },
  { id: 'celtic_menhir_warrior', name: 'Guerriera dei Menhir', element: 'Terra', faction: 'Celtica', rarity: 2, role: 'DPS Melee' },
  { id: 'egyptian_oasis_markswoman', name: 'Tiratrice dell’Oasi', element: 'Acqua', faction: 'Egizia', rarity: 2, role: 'DPS Ranged' },
  { id: 'yokai_huntress', name: 'Cacciatrice Yokai', element: 'Vento', faction: 'Japanese Yokai', rarity: 2, role: 'DPS Ranged' },
  { id: 'yokai_thunder_novice', name: 'Novizia del Tuono', element: 'Fulmine', faction: 'Japanese Yokai', rarity: 2, role: 'Mage AoE' },
  { id: 'yokai_shinobi_shadow', name: 'Ombra Shinobi', element: 'Oscurità', faction: 'Japanese Yokai', rarity: 2, role: 'Assassin' },
  { id: 'angelic_cantor', name: 'Cantora Angelica', element: 'Luce', faction: 'Angelica', rarity: 2, role: 'Support' },
  { id: 'egyptian_nile_healer', name: 'Curatrice del Nilo', element: 'Acqua', faction: 'Egizia', rarity: 2, role: 'Healer' },
  { id: 'cursed_bone_sibyl', name: 'Sibilla d’Ossa', element: 'Oscurità', faction: 'Cursed', rarity: 2, role: 'Control' },
  { id: 'demonic_infernal_adept', name: 'Adepta Infernale', element: 'Fuoco', faction: 'Demonica', rarity: 2, role: 'Hybrid' },
];

export const PLACEHOLDER_HERO_ASSET_REGISTRY_1STAR_2STAR: Record<string, PlaceholderAssetMap> = {
  greek_phalanx_recruit: {
    transparent: require('../../assets/heroes/greek_phalanx_recruit/transparent.png') as ImageSourcePropType,
    card: require('../../assets/heroes/greek_phalanx_recruit/card.png') as ImageSourcePropType,
    detail: require('../../assets/heroes/greek_phalanx_recruit/detail.png') as ImageSourcePropType,
    combat_base: require('../../assets/heroes/greek_phalanx_recruit/combat_base.png') as ImageSourcePropType,
  },
  demonic_infernal_handmaiden: {
    transparent: require('../../assets/heroes/demonic_infernal_handmaiden/transparent.png') as ImageSourcePropType,
    card: require('../../assets/heroes/demonic_infernal_handmaiden/card.png') as ImageSourcePropType,
    detail: require('../../assets/heroes/demonic_infernal_handmaiden/detail.png') as ImageSourcePropType,
    combat_base: require('../../assets/heroes/demonic_infernal_handmaiden/combat_base.png') as ImageSourcePropType,
  },
  egyptian_nile_guard: {
    transparent: require('../../assets/heroes/egyptian_nile_guard/transparent.png') as ImageSourcePropType,
    card: require('../../assets/heroes/egyptian_nile_guard/card.png') as ImageSourcePropType,
    detail: require('../../assets/heroes/egyptian_nile_guard/detail.png') as ImageSourcePropType,
    combat_base: require('../../assets/heroes/egyptian_nile_guard/combat_base.png') as ImageSourcePropType,
  },
  celtic_forest_archer: {
    transparent: require('../../assets/heroes/celtic_forest_archer/transparent.png') as ImageSourcePropType,
    card: require('../../assets/heroes/celtic_forest_archer/card.png') as ImageSourcePropType,
    detail: require('../../assets/heroes/celtic_forest_archer/detail.png') as ImageSourcePropType,
    combat_base: require('../../assets/heroes/celtic_forest_archer/combat_base.png') as ImageSourcePropType,
  },
  norse_rune_initiate: {
    transparent: require('../../assets/heroes/norse_rune_initiate/transparent.png') as ImageSourcePropType,
    card: require('../../assets/heroes/norse_rune_initiate/card.png') as ImageSourcePropType,
    detail: require('../../assets/heroes/norse_rune_initiate/detail.png') as ImageSourcePropType,
    combat_base: require('../../assets/heroes/norse_rune_initiate/combat_base.png') as ImageSourcePropType,
  },
  angelic_sanctuary_acolyte: {
    transparent: require('../../assets/heroes/angelic_sanctuary_acolyte/transparent.png') as ImageSourcePropType,
    card: require('../../assets/heroes/angelic_sanctuary_acolyte/card.png') as ImageSourcePropType,
    detail: require('../../assets/heroes/angelic_sanctuary_acolyte/detail.png') as ImageSourcePropType,
    combat_base: require('../../assets/heroes/angelic_sanctuary_acolyte/combat_base.png') as ImageSourcePropType,
  },
  angelic_sacred_novice: {
    transparent: require('../../assets/heroes/angelic_sacred_novice/transparent.png') as ImageSourcePropType,
    card: require('../../assets/heroes/angelic_sacred_novice/card.png') as ImageSourcePropType,
    detail: require('../../assets/heroes/angelic_sacred_novice/detail.png') as ImageSourcePropType,
    combat_base: require('../../assets/heroes/angelic_sacred_novice/combat_base.png') as ImageSourcePropType,
  },
  yokai_veiled_spirit: {
    transparent: require('../../assets/heroes/yokai_veiled_spirit/transparent.png') as ImageSourcePropType,
    card: require('../../assets/heroes/yokai_veiled_spirit/card.png') as ImageSourcePropType,
    detail: require('../../assets/heroes/yokai_veiled_spirit/detail.png') as ImageSourcePropType,
    combat_base: require('../../assets/heroes/yokai_veiled_spirit/combat_base.png') as ImageSourcePropType,
  },
  egyptian_temple_guardian: {
    transparent: require('../../assets/heroes/egyptian_temple_guardian/transparent.png') as ImageSourcePropType,
    card: require('../../assets/heroes/egyptian_temple_guardian/card.png') as ImageSourcePropType,
    detail: require('../../assets/heroes/egyptian_temple_guardian/detail.png') as ImageSourcePropType,
    combat_base: require('../../assets/heroes/egyptian_temple_guardian/combat_base.png') as ImageSourcePropType,
  },
  norse_valhalla_warden: {
    transparent: require('../../assets/heroes/norse_valhalla_warden/transparent.png') as ImageSourcePropType,
    card: require('../../assets/heroes/norse_valhalla_warden/card.png') as ImageSourcePropType,
    detail: require('../../assets/heroes/norse_valhalla_warden/detail.png') as ImageSourcePropType,
    combat_base: require('../../assets/heroes/norse_valhalla_warden/combat_base.png') as ImageSourcePropType,
  },
  egyptian_desert_blade: {
    transparent: require('../../assets/heroes/egyptian_desert_blade/transparent.png') as ImageSourcePropType,
    card: require('../../assets/heroes/egyptian_desert_blade/card.png') as ImageSourcePropType,
    detail: require('../../assets/heroes/egyptian_desert_blade/detail.png') as ImageSourcePropType,
    combat_base: require('../../assets/heroes/egyptian_desert_blade/combat_base.png') as ImageSourcePropType,
  },
  celtic_menhir_warrior: {
    transparent: require('../../assets/heroes/celtic_menhir_warrior/transparent.png') as ImageSourcePropType,
    card: require('../../assets/heroes/celtic_menhir_warrior/card.png') as ImageSourcePropType,
    detail: require('../../assets/heroes/celtic_menhir_warrior/detail.png') as ImageSourcePropType,
    combat_base: require('../../assets/heroes/celtic_menhir_warrior/combat_base.png') as ImageSourcePropType,
  },
  egyptian_oasis_markswoman: {
    transparent: require('../../assets/heroes/egyptian_oasis_markswoman/transparent.png') as ImageSourcePropType,
    card: require('../../assets/heroes/egyptian_oasis_markswoman/card.png') as ImageSourcePropType,
    detail: require('../../assets/heroes/egyptian_oasis_markswoman/detail.png') as ImageSourcePropType,
    combat_base: require('../../assets/heroes/egyptian_oasis_markswoman/combat_base.png') as ImageSourcePropType,
  },
  yokai_huntress: {
    transparent: require('../../assets/heroes/yokai_huntress/transparent.png') as ImageSourcePropType,
    card: require('../../assets/heroes/yokai_huntress/card.png') as ImageSourcePropType,
    detail: require('../../assets/heroes/yokai_huntress/detail.png') as ImageSourcePropType,
    combat_base: require('../../assets/heroes/yokai_huntress/combat_base.png') as ImageSourcePropType,
  },
  yokai_thunder_novice: {
    transparent: require('../../assets/heroes/yokai_thunder_novice/transparent.png') as ImageSourcePropType,
    card: require('../../assets/heroes/yokai_thunder_novice/card.png') as ImageSourcePropType,
    detail: require('../../assets/heroes/yokai_thunder_novice/detail.png') as ImageSourcePropType,
    combat_base: require('../../assets/heroes/yokai_thunder_novice/combat_base.png') as ImageSourcePropType,
  },
  yokai_shinobi_shadow: {
    transparent: require('../../assets/heroes/yokai_shinobi_shadow/transparent.png') as ImageSourcePropType,
    card: require('../../assets/heroes/yokai_shinobi_shadow/card.png') as ImageSourcePropType,
    detail: require('../../assets/heroes/yokai_shinobi_shadow/detail.png') as ImageSourcePropType,
    combat_base: require('../../assets/heroes/yokai_shinobi_shadow/combat_base.png') as ImageSourcePropType,
  },
  angelic_cantor: {
    transparent: require('../../assets/heroes/angelic_cantor/transparent.png') as ImageSourcePropType,
    card: require('../../assets/heroes/angelic_cantor/card.png') as ImageSourcePropType,
    detail: require('../../assets/heroes/angelic_cantor/detail.png') as ImageSourcePropType,
    combat_base: require('../../assets/heroes/angelic_cantor/combat_base.png') as ImageSourcePropType,
  },
  egyptian_nile_healer: {
    transparent: require('../../assets/heroes/egyptian_nile_healer/transparent.png') as ImageSourcePropType,
    card: require('../../assets/heroes/egyptian_nile_healer/card.png') as ImageSourcePropType,
    detail: require('../../assets/heroes/egyptian_nile_healer/detail.png') as ImageSourcePropType,
    combat_base: require('../../assets/heroes/egyptian_nile_healer/combat_base.png') as ImageSourcePropType,
  },
  cursed_bone_sibyl: {
    transparent: require('../../assets/heroes/cursed_bone_sibyl/transparent.png') as ImageSourcePropType,
    card: require('../../assets/heroes/cursed_bone_sibyl/card.png') as ImageSourcePropType,
    detail: require('../../assets/heroes/cursed_bone_sibyl/detail.png') as ImageSourcePropType,
    combat_base: require('../../assets/heroes/cursed_bone_sibyl/combat_base.png') as ImageSourcePropType,
  },
  demonic_infernal_adept: {
    transparent: require('../../assets/heroes/demonic_infernal_adept/transparent.png') as ImageSourcePropType,
    card: require('../../assets/heroes/demonic_infernal_adept/card.png') as ImageSourcePropType,
    detail: require('../../assets/heroes/demonic_infernal_adept/detail.png') as ImageSourcePropType,
    combat_base: require('../../assets/heroes/demonic_infernal_adept/combat_base.png') as ImageSourcePropType,
  },
};

export const PLACEHOLDER_HERO_CONTRACTS_1STAR_2STAR: Record<string, HeroAssetContract> = {
  greek_phalanx_recruit: {
    id: 'greek_phalanx_recruit',
    variants: {
      splash: require('../../assets/heroes/greek_phalanx_recruit/splash.jpg') as ImageSourcePropType,
      portrait: require('../../assets/heroes/greek_phalanx_recruit/splash.jpg') as ImageSourcePropType,
      card: require('../../assets/heroes/greek_phalanx_recruit/card.png') as ImageSourcePropType,
      detail: require('../../assets/heroes/greek_phalanx_recruit/detail.png') as ImageSourcePropType,
      fullscreen: require('../../assets/heroes/greek_phalanx_recruit/fullscreen.png') as ImageSourcePropType,
      transparent: require('../../assets/heroes/greek_phalanx_recruit/transparent.png') as ImageSourcePropType,
      combat_base: require('../../assets/heroes/greek_phalanx_recruit/combat_base.png') as ImageSourcePropType,
    },
    crop: {
      portraitFocusY: 0.35,
      cardFocusY: 0.35,
      detailFocusY: 0.35,
      sourceAspect: 'portrait',
    },
    viewer: {
      fullscreenVariant: 'fullscreen',
      fullscreenOrientation: 'portrait',
      useContain: true,
      allowDestructiveCrop: false,
    },
    battle: {
      defaultState: 'idle',
      useStateSprites: true,
      useRuntimeSheets: true,
      removeDefaultGlow: true,
      useLegacyDefaultMotion: false,
      runtimeRenderScale: 1.0,
    },
    ui: {
      home: { variant: 'transparent', resizeMode: 'contain', focusY: 0.5, scale: 1.0 },
      card: { variant: 'card', resizeMode: 'contain', focusY: 0.5, scale: 1.0 },
      detailIcon: { variant: 'detail', resizeMode: 'contain', focusY: 0.5, scale: 1.0 },
      selectedPreview: { variant: 'portrait', resizeMode: 'contain', focusY: 0.5, scale: 1.0 },
      fullscreen: { variant: 'fullscreen', resizeMode: 'contain', focusY: 0.5, scale: 1.0, verticalPriority: true },
    },
    runtimeSheets: {
      idle: makeRuntimeSheet(require('../../assets/heroes/greek_phalanx_recruit/runtime/idle_sheet.png') as ImageSourcePropType, 6, 6, 8, true),
      attack: makeRuntimeSheet(require('../../assets/heroes/greek_phalanx_recruit/runtime/attack_sheet.png') as ImageSourcePropType, 5, 5, 12, false),
      skill: makeRuntimeSheet(require('../../assets/heroes/greek_phalanx_recruit/runtime/skill_sheet.png') as ImageSourcePropType, 6, 6, 12, false),
      hit: makeRuntimeSheet(require('../../assets/heroes/greek_phalanx_recruit/runtime/hit_sheet.png') as ImageSourcePropType, 5, 5, 10, false),
      death: makeRuntimeSheet(require('../../assets/heroes/greek_phalanx_recruit/runtime/death_sheet.png') as ImageSourcePropType, 6, 6, 8, false),
    },
  },
  demonic_infernal_handmaiden: {
    id: 'demonic_infernal_handmaiden',
    variants: {
      splash: require('../../assets/heroes/demonic_infernal_handmaiden/splash.jpg') as ImageSourcePropType,
      portrait: require('../../assets/heroes/demonic_infernal_handmaiden/splash.jpg') as ImageSourcePropType,
      card: require('../../assets/heroes/demonic_infernal_handmaiden/card.png') as ImageSourcePropType,
      detail: require('../../assets/heroes/demonic_infernal_handmaiden/detail.png') as ImageSourcePropType,
      fullscreen: require('../../assets/heroes/demonic_infernal_handmaiden/fullscreen.png') as ImageSourcePropType,
      transparent: require('../../assets/heroes/demonic_infernal_handmaiden/transparent.png') as ImageSourcePropType,
      combat_base: require('../../assets/heroes/demonic_infernal_handmaiden/combat_base.png') as ImageSourcePropType,
    },
    crop: {
      portraitFocusY: 0.35,
      cardFocusY: 0.35,
      detailFocusY: 0.35,
      sourceAspect: 'portrait',
    },
    viewer: {
      fullscreenVariant: 'fullscreen',
      fullscreenOrientation: 'portrait',
      useContain: true,
      allowDestructiveCrop: false,
    },
    battle: {
      defaultState: 'idle',
      useStateSprites: true,
      useRuntimeSheets: true,
      removeDefaultGlow: true,
      useLegacyDefaultMotion: false,
      runtimeRenderScale: 1.0,
    },
    ui: {
      home: { variant: 'transparent', resizeMode: 'contain', focusY: 0.5, scale: 1.0 },
      card: { variant: 'card', resizeMode: 'contain', focusY: 0.5, scale: 1.0 },
      detailIcon: { variant: 'detail', resizeMode: 'contain', focusY: 0.5, scale: 1.0 },
      selectedPreview: { variant: 'portrait', resizeMode: 'contain', focusY: 0.5, scale: 1.0 },
      fullscreen: { variant: 'fullscreen', resizeMode: 'contain', focusY: 0.5, scale: 1.0, verticalPriority: true },
    },
    runtimeSheets: {
      idle: makeRuntimeSheet(require('../../assets/heroes/demonic_infernal_handmaiden/runtime/idle_sheet.png') as ImageSourcePropType, 6, 6, 8, true),
      attack: makeRuntimeSheet(require('../../assets/heroes/demonic_infernal_handmaiden/runtime/attack_sheet.png') as ImageSourcePropType, 5, 5, 12, false),
      skill: makeRuntimeSheet(require('../../assets/heroes/demonic_infernal_handmaiden/runtime/skill_sheet.png') as ImageSourcePropType, 6, 6, 12, false),
      hit: makeRuntimeSheet(require('../../assets/heroes/demonic_infernal_handmaiden/runtime/hit_sheet.png') as ImageSourcePropType, 5, 5, 10, false),
      death: makeRuntimeSheet(require('../../assets/heroes/demonic_infernal_handmaiden/runtime/death_sheet.png') as ImageSourcePropType, 6, 6, 8, false),
    },
  },
  egyptian_nile_guard: {
    id: 'egyptian_nile_guard',
    variants: {
      splash: require('../../assets/heroes/egyptian_nile_guard/splash.jpg') as ImageSourcePropType,
      portrait: require('../../assets/heroes/egyptian_nile_guard/splash.jpg') as ImageSourcePropType,
      card: require('../../assets/heroes/egyptian_nile_guard/card.png') as ImageSourcePropType,
      detail: require('../../assets/heroes/egyptian_nile_guard/detail.png') as ImageSourcePropType,
      fullscreen: require('../../assets/heroes/egyptian_nile_guard/fullscreen.png') as ImageSourcePropType,
      transparent: require('../../assets/heroes/egyptian_nile_guard/transparent.png') as ImageSourcePropType,
      combat_base: require('../../assets/heroes/egyptian_nile_guard/combat_base.png') as ImageSourcePropType,
    },
    crop: {
      portraitFocusY: 0.35,
      cardFocusY: 0.35,
      detailFocusY: 0.35,
      sourceAspect: 'portrait',
    },
    viewer: {
      fullscreenVariant: 'fullscreen',
      fullscreenOrientation: 'portrait',
      useContain: true,
      allowDestructiveCrop: false,
    },
    battle: {
      defaultState: 'idle',
      useStateSprites: true,
      useRuntimeSheets: true,
      removeDefaultGlow: true,
      useLegacyDefaultMotion: false,
      runtimeRenderScale: 1.0,
    },
    ui: {
      home: { variant: 'transparent', resizeMode: 'contain', focusY: 0.5, scale: 1.0 },
      card: { variant: 'card', resizeMode: 'contain', focusY: 0.5, scale: 1.0 },
      detailIcon: { variant: 'detail', resizeMode: 'contain', focusY: 0.5, scale: 1.0 },
      selectedPreview: { variant: 'portrait', resizeMode: 'contain', focusY: 0.5, scale: 1.0 },
      fullscreen: { variant: 'fullscreen', resizeMode: 'contain', focusY: 0.5, scale: 1.0, verticalPriority: true },
    },
    runtimeSheets: {
      idle: makeRuntimeSheet(require('../../assets/heroes/egyptian_nile_guard/runtime/idle_sheet.png') as ImageSourcePropType, 6, 6, 8, true),
      attack: makeRuntimeSheet(require('../../assets/heroes/egyptian_nile_guard/runtime/attack_sheet.png') as ImageSourcePropType, 5, 5, 12, false),
      skill: makeRuntimeSheet(require('../../assets/heroes/egyptian_nile_guard/runtime/skill_sheet.png') as ImageSourcePropType, 6, 6, 12, false),
      hit: makeRuntimeSheet(require('../../assets/heroes/egyptian_nile_guard/runtime/hit_sheet.png') as ImageSourcePropType, 5, 5, 10, false),
      death: makeRuntimeSheet(require('../../assets/heroes/egyptian_nile_guard/runtime/death_sheet.png') as ImageSourcePropType, 6, 6, 8, false),
    },
  },
  celtic_forest_archer: {
    id: 'celtic_forest_archer',
    variants: {
      splash: require('../../assets/heroes/celtic_forest_archer/splash.jpg') as ImageSourcePropType,
      portrait: require('../../assets/heroes/celtic_forest_archer/splash.jpg') as ImageSourcePropType,
      card: require('../../assets/heroes/celtic_forest_archer/card.png') as ImageSourcePropType,
      detail: require('../../assets/heroes/celtic_forest_archer/detail.png') as ImageSourcePropType,
      fullscreen: require('../../assets/heroes/celtic_forest_archer/fullscreen.png') as ImageSourcePropType,
      transparent: require('../../assets/heroes/celtic_forest_archer/transparent.png') as ImageSourcePropType,
      combat_base: require('../../assets/heroes/celtic_forest_archer/combat_base.png') as ImageSourcePropType,
    },
    crop: {
      portraitFocusY: 0.35,
      cardFocusY: 0.35,
      detailFocusY: 0.35,
      sourceAspect: 'portrait',
    },
    viewer: {
      fullscreenVariant: 'fullscreen',
      fullscreenOrientation: 'portrait',
      useContain: true,
      allowDestructiveCrop: false,
    },
    battle: {
      defaultState: 'idle',
      useStateSprites: true,
      useRuntimeSheets: true,
      removeDefaultGlow: true,
      useLegacyDefaultMotion: false,
      runtimeRenderScale: 1.0,
    },
    ui: {
      home: { variant: 'transparent', resizeMode: 'contain', focusY: 0.5, scale: 1.0 },
      card: { variant: 'card', resizeMode: 'contain', focusY: 0.5, scale: 1.0 },
      detailIcon: { variant: 'detail', resizeMode: 'contain', focusY: 0.5, scale: 1.0 },
      selectedPreview: { variant: 'portrait', resizeMode: 'contain', focusY: 0.5, scale: 1.0 },
      fullscreen: { variant: 'fullscreen', resizeMode: 'contain', focusY: 0.5, scale: 1.0, verticalPriority: true },
    },
    runtimeSheets: {
      idle: makeRuntimeSheet(require('../../assets/heroes/celtic_forest_archer/runtime/idle_sheet.png') as ImageSourcePropType, 6, 6, 8, true),
      attack: makeRuntimeSheet(require('../../assets/heroes/celtic_forest_archer/runtime/attack_sheet.png') as ImageSourcePropType, 5, 5, 12, false),
      skill: makeRuntimeSheet(require('../../assets/heroes/celtic_forest_archer/runtime/skill_sheet.png') as ImageSourcePropType, 6, 6, 12, false),
      hit: makeRuntimeSheet(require('../../assets/heroes/celtic_forest_archer/runtime/hit_sheet.png') as ImageSourcePropType, 5, 5, 10, false),
      death: makeRuntimeSheet(require('../../assets/heroes/celtic_forest_archer/runtime/death_sheet.png') as ImageSourcePropType, 6, 6, 8, false),
    },
  },
  norse_rune_initiate: {
    id: 'norse_rune_initiate',
    variants: {
      splash: require('../../assets/heroes/norse_rune_initiate/splash.jpg') as ImageSourcePropType,
      portrait: require('../../assets/heroes/norse_rune_initiate/splash.jpg') as ImageSourcePropType,
      card: require('../../assets/heroes/norse_rune_initiate/card.png') as ImageSourcePropType,
      detail: require('../../assets/heroes/norse_rune_initiate/detail.png') as ImageSourcePropType,
      fullscreen: require('../../assets/heroes/norse_rune_initiate/fullscreen.png') as ImageSourcePropType,
      transparent: require('../../assets/heroes/norse_rune_initiate/transparent.png') as ImageSourcePropType,
      combat_base: require('../../assets/heroes/norse_rune_initiate/combat_base.png') as ImageSourcePropType,
    },
    crop: {
      portraitFocusY: 0.35,
      cardFocusY: 0.35,
      detailFocusY: 0.35,
      sourceAspect: 'portrait',
    },
    viewer: {
      fullscreenVariant: 'fullscreen',
      fullscreenOrientation: 'portrait',
      useContain: true,
      allowDestructiveCrop: false,
    },
    battle: {
      defaultState: 'idle',
      useStateSprites: true,
      useRuntimeSheets: true,
      removeDefaultGlow: true,
      useLegacyDefaultMotion: false,
      runtimeRenderScale: 1.0,
    },
    ui: {
      home: { variant: 'transparent', resizeMode: 'contain', focusY: 0.5, scale: 1.0 },
      card: { variant: 'card', resizeMode: 'contain', focusY: 0.5, scale: 1.0 },
      detailIcon: { variant: 'detail', resizeMode: 'contain', focusY: 0.5, scale: 1.0 },
      selectedPreview: { variant: 'portrait', resizeMode: 'contain', focusY: 0.5, scale: 1.0 },
      fullscreen: { variant: 'fullscreen', resizeMode: 'contain', focusY: 0.5, scale: 1.0, verticalPriority: true },
    },
    runtimeSheets: {
      idle: makeRuntimeSheet(require('../../assets/heroes/norse_rune_initiate/runtime/idle_sheet.png') as ImageSourcePropType, 6, 6, 8, true),
      attack: makeRuntimeSheet(require('../../assets/heroes/norse_rune_initiate/runtime/attack_sheet.png') as ImageSourcePropType, 5, 5, 12, false),
      skill: makeRuntimeSheet(require('../../assets/heroes/norse_rune_initiate/runtime/skill_sheet.png') as ImageSourcePropType, 6, 6, 12, false),
      hit: makeRuntimeSheet(require('../../assets/heroes/norse_rune_initiate/runtime/hit_sheet.png') as ImageSourcePropType, 5, 5, 10, false),
      death: makeRuntimeSheet(require('../../assets/heroes/norse_rune_initiate/runtime/death_sheet.png') as ImageSourcePropType, 6, 6, 8, false),
    },
  },
  angelic_sanctuary_acolyte: {
    id: 'angelic_sanctuary_acolyte',
    variants: {
      splash: require('../../assets/heroes/angelic_sanctuary_acolyte/splash.jpg') as ImageSourcePropType,
      portrait: require('../../assets/heroes/angelic_sanctuary_acolyte/splash.jpg') as ImageSourcePropType,
      card: require('../../assets/heroes/angelic_sanctuary_acolyte/card.png') as ImageSourcePropType,
      detail: require('../../assets/heroes/angelic_sanctuary_acolyte/detail.png') as ImageSourcePropType,
      fullscreen: require('../../assets/heroes/angelic_sanctuary_acolyte/fullscreen.png') as ImageSourcePropType,
      transparent: require('../../assets/heroes/angelic_sanctuary_acolyte/transparent.png') as ImageSourcePropType,
      combat_base: require('../../assets/heroes/angelic_sanctuary_acolyte/combat_base.png') as ImageSourcePropType,
    },
    crop: {
      portraitFocusY: 0.35,
      cardFocusY: 0.35,
      detailFocusY: 0.35,
      sourceAspect: 'portrait',
    },
    viewer: {
      fullscreenVariant: 'fullscreen',
      fullscreenOrientation: 'portrait',
      useContain: true,
      allowDestructiveCrop: false,
    },
    battle: {
      defaultState: 'idle',
      useStateSprites: true,
      useRuntimeSheets: true,
      removeDefaultGlow: true,
      useLegacyDefaultMotion: false,
      runtimeRenderScale: 1.0,
    },
    ui: {
      home: { variant: 'transparent', resizeMode: 'contain', focusY: 0.5, scale: 1.0 },
      card: { variant: 'card', resizeMode: 'contain', focusY: 0.5, scale: 1.0 },
      detailIcon: { variant: 'detail', resizeMode: 'contain', focusY: 0.5, scale: 1.0 },
      selectedPreview: { variant: 'portrait', resizeMode: 'contain', focusY: 0.5, scale: 1.0 },
      fullscreen: { variant: 'fullscreen', resizeMode: 'contain', focusY: 0.5, scale: 1.0, verticalPriority: true },
    },
    runtimeSheets: {
      idle: makeRuntimeSheet(require('../../assets/heroes/angelic_sanctuary_acolyte/runtime/idle_sheet.png') as ImageSourcePropType, 6, 6, 8, true),
      attack: makeRuntimeSheet(require('../../assets/heroes/angelic_sanctuary_acolyte/runtime/attack_sheet.png') as ImageSourcePropType, 5, 5, 12, false),
      skill: makeRuntimeSheet(require('../../assets/heroes/angelic_sanctuary_acolyte/runtime/skill_sheet.png') as ImageSourcePropType, 6, 6, 12, false),
      hit: makeRuntimeSheet(require('../../assets/heroes/angelic_sanctuary_acolyte/runtime/hit_sheet.png') as ImageSourcePropType, 5, 5, 10, false),
      death: makeRuntimeSheet(require('../../assets/heroes/angelic_sanctuary_acolyte/runtime/death_sheet.png') as ImageSourcePropType, 6, 6, 8, false),
    },
  },
  angelic_sacred_novice: {
    id: 'angelic_sacred_novice',
    variants: {
      splash: require('../../assets/heroes/angelic_sacred_novice/splash.jpg') as ImageSourcePropType,
      portrait: require('../../assets/heroes/angelic_sacred_novice/splash.jpg') as ImageSourcePropType,
      card: require('../../assets/heroes/angelic_sacred_novice/card.png') as ImageSourcePropType,
      detail: require('../../assets/heroes/angelic_sacred_novice/detail.png') as ImageSourcePropType,
      fullscreen: require('../../assets/heroes/angelic_sacred_novice/fullscreen.png') as ImageSourcePropType,
      transparent: require('../../assets/heroes/angelic_sacred_novice/transparent.png') as ImageSourcePropType,
      combat_base: require('../../assets/heroes/angelic_sacred_novice/combat_base.png') as ImageSourcePropType,
    },
    crop: {
      portraitFocusY: 0.35,
      cardFocusY: 0.35,
      detailFocusY: 0.35,
      sourceAspect: 'portrait',
    },
    viewer: {
      fullscreenVariant: 'fullscreen',
      fullscreenOrientation: 'portrait',
      useContain: true,
      allowDestructiveCrop: false,
    },
    battle: {
      defaultState: 'idle',
      useStateSprites: true,
      useRuntimeSheets: true,
      removeDefaultGlow: true,
      useLegacyDefaultMotion: false,
      runtimeRenderScale: 1.0,
    },
    ui: {
      home: { variant: 'transparent', resizeMode: 'contain', focusY: 0.5, scale: 1.0 },
      card: { variant: 'card', resizeMode: 'contain', focusY: 0.5, scale: 1.0 },
      detailIcon: { variant: 'detail', resizeMode: 'contain', focusY: 0.5, scale: 1.0 },
      selectedPreview: { variant: 'portrait', resizeMode: 'contain', focusY: 0.5, scale: 1.0 },
      fullscreen: { variant: 'fullscreen', resizeMode: 'contain', focusY: 0.5, scale: 1.0, verticalPriority: true },
    },
    runtimeSheets: {
      idle: makeRuntimeSheet(require('../../assets/heroes/angelic_sacred_novice/runtime/idle_sheet.png') as ImageSourcePropType, 6, 6, 8, true),
      attack: makeRuntimeSheet(require('../../assets/heroes/angelic_sacred_novice/runtime/attack_sheet.png') as ImageSourcePropType, 5, 5, 12, false),
      skill: makeRuntimeSheet(require('../../assets/heroes/angelic_sacred_novice/runtime/skill_sheet.png') as ImageSourcePropType, 6, 6, 12, false),
      hit: makeRuntimeSheet(require('../../assets/heroes/angelic_sacred_novice/runtime/hit_sheet.png') as ImageSourcePropType, 5, 5, 10, false),
      death: makeRuntimeSheet(require('../../assets/heroes/angelic_sacred_novice/runtime/death_sheet.png') as ImageSourcePropType, 6, 6, 8, false),
    },
  },
  yokai_veiled_spirit: {
    id: 'yokai_veiled_spirit',
    variants: {
      splash: require('../../assets/heroes/yokai_veiled_spirit/splash.jpg') as ImageSourcePropType,
      portrait: require('../../assets/heroes/yokai_veiled_spirit/splash.jpg') as ImageSourcePropType,
      card: require('../../assets/heroes/yokai_veiled_spirit/card.png') as ImageSourcePropType,
      detail: require('../../assets/heroes/yokai_veiled_spirit/detail.png') as ImageSourcePropType,
      fullscreen: require('../../assets/heroes/yokai_veiled_spirit/fullscreen.png') as ImageSourcePropType,
      transparent: require('../../assets/heroes/yokai_veiled_spirit/transparent.png') as ImageSourcePropType,
      combat_base: require('../../assets/heroes/yokai_veiled_spirit/combat_base.png') as ImageSourcePropType,
    },
    crop: {
      portraitFocusY: 0.35,
      cardFocusY: 0.35,
      detailFocusY: 0.35,
      sourceAspect: 'portrait',
    },
    viewer: {
      fullscreenVariant: 'fullscreen',
      fullscreenOrientation: 'portrait',
      useContain: true,
      allowDestructiveCrop: false,
    },
    battle: {
      defaultState: 'idle',
      useStateSprites: true,
      useRuntimeSheets: true,
      removeDefaultGlow: true,
      useLegacyDefaultMotion: false,
      runtimeRenderScale: 1.0,
    },
    ui: {
      home: { variant: 'transparent', resizeMode: 'contain', focusY: 0.5, scale: 1.0 },
      card: { variant: 'card', resizeMode: 'contain', focusY: 0.5, scale: 1.0 },
      detailIcon: { variant: 'detail', resizeMode: 'contain', focusY: 0.5, scale: 1.0 },
      selectedPreview: { variant: 'portrait', resizeMode: 'contain', focusY: 0.5, scale: 1.0 },
      fullscreen: { variant: 'fullscreen', resizeMode: 'contain', focusY: 0.5, scale: 1.0, verticalPriority: true },
    },
    runtimeSheets: {
      idle: makeRuntimeSheet(require('../../assets/heroes/yokai_veiled_spirit/runtime/idle_sheet.png') as ImageSourcePropType, 6, 6, 8, true),
      attack: makeRuntimeSheet(require('../../assets/heroes/yokai_veiled_spirit/runtime/attack_sheet.png') as ImageSourcePropType, 5, 5, 12, false),
      skill: makeRuntimeSheet(require('../../assets/heroes/yokai_veiled_spirit/runtime/skill_sheet.png') as ImageSourcePropType, 6, 6, 12, false),
      hit: makeRuntimeSheet(require('../../assets/heroes/yokai_veiled_spirit/runtime/hit_sheet.png') as ImageSourcePropType, 5, 5, 10, false),
      death: makeRuntimeSheet(require('../../assets/heroes/yokai_veiled_spirit/runtime/death_sheet.png') as ImageSourcePropType, 6, 6, 8, false),
    },
  },
  egyptian_temple_guardian: {
    id: 'egyptian_temple_guardian',
    variants: {
      splash: require('../../assets/heroes/egyptian_temple_guardian/splash.jpg') as ImageSourcePropType,
      portrait: require('../../assets/heroes/egyptian_temple_guardian/splash.jpg') as ImageSourcePropType,
      card: require('../../assets/heroes/egyptian_temple_guardian/card.png') as ImageSourcePropType,
      detail: require('../../assets/heroes/egyptian_temple_guardian/detail.png') as ImageSourcePropType,
      fullscreen: require('../../assets/heroes/egyptian_temple_guardian/fullscreen.png') as ImageSourcePropType,
      transparent: require('../../assets/heroes/egyptian_temple_guardian/transparent.png') as ImageSourcePropType,
      combat_base: require('../../assets/heroes/egyptian_temple_guardian/combat_base.png') as ImageSourcePropType,
    },
    crop: {
      portraitFocusY: 0.35,
      cardFocusY: 0.35,
      detailFocusY: 0.35,
      sourceAspect: 'portrait',
    },
    viewer: {
      fullscreenVariant: 'fullscreen',
      fullscreenOrientation: 'portrait',
      useContain: true,
      allowDestructiveCrop: false,
    },
    battle: {
      defaultState: 'idle',
      useStateSprites: true,
      useRuntimeSheets: true,
      removeDefaultGlow: true,
      useLegacyDefaultMotion: false,
      runtimeRenderScale: 1.0,
    },
    ui: {
      home: { variant: 'transparent', resizeMode: 'contain', focusY: 0.5, scale: 1.0 },
      card: { variant: 'card', resizeMode: 'contain', focusY: 0.5, scale: 1.0 },
      detailIcon: { variant: 'detail', resizeMode: 'contain', focusY: 0.5, scale: 1.0 },
      selectedPreview: { variant: 'portrait', resizeMode: 'contain', focusY: 0.5, scale: 1.0 },
      fullscreen: { variant: 'fullscreen', resizeMode: 'contain', focusY: 0.5, scale: 1.0, verticalPriority: true },
    },
    runtimeSheets: {
      idle: makeRuntimeSheet(require('../../assets/heroes/egyptian_temple_guardian/runtime/idle_sheet.png') as ImageSourcePropType, 6, 6, 8, true),
      attack: makeRuntimeSheet(require('../../assets/heroes/egyptian_temple_guardian/runtime/attack_sheet.png') as ImageSourcePropType, 5, 5, 12, false),
      skill: makeRuntimeSheet(require('../../assets/heroes/egyptian_temple_guardian/runtime/skill_sheet.png') as ImageSourcePropType, 6, 6, 12, false),
      hit: makeRuntimeSheet(require('../../assets/heroes/egyptian_temple_guardian/runtime/hit_sheet.png') as ImageSourcePropType, 5, 5, 10, false),
      death: makeRuntimeSheet(require('../../assets/heroes/egyptian_temple_guardian/runtime/death_sheet.png') as ImageSourcePropType, 6, 6, 8, false),
    },
  },
  norse_valhalla_warden: {
    id: 'norse_valhalla_warden',
    variants: {
      splash: require('../../assets/heroes/norse_valhalla_warden/splash.jpg') as ImageSourcePropType,
      portrait: require('../../assets/heroes/norse_valhalla_warden/splash.jpg') as ImageSourcePropType,
      card: require('../../assets/heroes/norse_valhalla_warden/card.png') as ImageSourcePropType,
      detail: require('../../assets/heroes/norse_valhalla_warden/detail.png') as ImageSourcePropType,
      fullscreen: require('../../assets/heroes/norse_valhalla_warden/fullscreen.png') as ImageSourcePropType,
      transparent: require('../../assets/heroes/norse_valhalla_warden/transparent.png') as ImageSourcePropType,
      combat_base: require('../../assets/heroes/norse_valhalla_warden/combat_base.png') as ImageSourcePropType,
    },
    crop: {
      portraitFocusY: 0.35,
      cardFocusY: 0.35,
      detailFocusY: 0.35,
      sourceAspect: 'portrait',
    },
    viewer: {
      fullscreenVariant: 'fullscreen',
      fullscreenOrientation: 'portrait',
      useContain: true,
      allowDestructiveCrop: false,
    },
    battle: {
      defaultState: 'idle',
      useStateSprites: true,
      useRuntimeSheets: true,
      removeDefaultGlow: true,
      useLegacyDefaultMotion: false,
      runtimeRenderScale: 1.0,
    },
    ui: {
      home: { variant: 'transparent', resizeMode: 'contain', focusY: 0.5, scale: 1.0 },
      card: { variant: 'card', resizeMode: 'contain', focusY: 0.5, scale: 1.0 },
      detailIcon: { variant: 'detail', resizeMode: 'contain', focusY: 0.5, scale: 1.0 },
      selectedPreview: { variant: 'portrait', resizeMode: 'contain', focusY: 0.5, scale: 1.0 },
      fullscreen: { variant: 'fullscreen', resizeMode: 'contain', focusY: 0.5, scale: 1.0, verticalPriority: true },
    },
    runtimeSheets: {
      idle: makeRuntimeSheet(require('../../assets/heroes/norse_valhalla_warden/runtime/idle_sheet.png') as ImageSourcePropType, 6, 6, 8, true),
      attack: makeRuntimeSheet(require('../../assets/heroes/norse_valhalla_warden/runtime/attack_sheet.png') as ImageSourcePropType, 5, 5, 12, false),
      skill: makeRuntimeSheet(require('../../assets/heroes/norse_valhalla_warden/runtime/skill_sheet.png') as ImageSourcePropType, 6, 6, 12, false),
      hit: makeRuntimeSheet(require('../../assets/heroes/norse_valhalla_warden/runtime/hit_sheet.png') as ImageSourcePropType, 5, 5, 10, false),
      death: makeRuntimeSheet(require('../../assets/heroes/norse_valhalla_warden/runtime/death_sheet.png') as ImageSourcePropType, 6, 6, 8, false),
    },
  },
  egyptian_desert_blade: {
    id: 'egyptian_desert_blade',
    variants: {
      splash: require('../../assets/heroes/egyptian_desert_blade/splash.jpg') as ImageSourcePropType,
      portrait: require('../../assets/heroes/egyptian_desert_blade/splash.jpg') as ImageSourcePropType,
      card: require('../../assets/heroes/egyptian_desert_blade/card.png') as ImageSourcePropType,
      detail: require('../../assets/heroes/egyptian_desert_blade/detail.png') as ImageSourcePropType,
      fullscreen: require('../../assets/heroes/egyptian_desert_blade/fullscreen.png') as ImageSourcePropType,
      transparent: require('../../assets/heroes/egyptian_desert_blade/transparent.png') as ImageSourcePropType,
      combat_base: require('../../assets/heroes/egyptian_desert_blade/combat_base.png') as ImageSourcePropType,
    },
    crop: {
      portraitFocusY: 0.35,
      cardFocusY: 0.35,
      detailFocusY: 0.35,
      sourceAspect: 'portrait',
    },
    viewer: {
      fullscreenVariant: 'fullscreen',
      fullscreenOrientation: 'portrait',
      useContain: true,
      allowDestructiveCrop: false,
    },
    battle: {
      defaultState: 'idle',
      useStateSprites: true,
      useRuntimeSheets: true,
      removeDefaultGlow: true,
      useLegacyDefaultMotion: false,
      runtimeRenderScale: 1.0,
    },
    ui: {
      home: { variant: 'transparent', resizeMode: 'contain', focusY: 0.5, scale: 1.0 },
      card: { variant: 'card', resizeMode: 'contain', focusY: 0.5, scale: 1.0 },
      detailIcon: { variant: 'detail', resizeMode: 'contain', focusY: 0.5, scale: 1.0 },
      selectedPreview: { variant: 'portrait', resizeMode: 'contain', focusY: 0.5, scale: 1.0 },
      fullscreen: { variant: 'fullscreen', resizeMode: 'contain', focusY: 0.5, scale: 1.0, verticalPriority: true },
    },
    runtimeSheets: {
      idle: makeRuntimeSheet(require('../../assets/heroes/egyptian_desert_blade/runtime/idle_sheet.png') as ImageSourcePropType, 6, 6, 8, true),
      attack: makeRuntimeSheet(require('../../assets/heroes/egyptian_desert_blade/runtime/attack_sheet.png') as ImageSourcePropType, 5, 5, 12, false),
      skill: makeRuntimeSheet(require('../../assets/heroes/egyptian_desert_blade/runtime/skill_sheet.png') as ImageSourcePropType, 6, 6, 12, false),
      hit: makeRuntimeSheet(require('../../assets/heroes/egyptian_desert_blade/runtime/hit_sheet.png') as ImageSourcePropType, 5, 5, 10, false),
      death: makeRuntimeSheet(require('../../assets/heroes/egyptian_desert_blade/runtime/death_sheet.png') as ImageSourcePropType, 6, 6, 8, false),
    },
  },
  celtic_menhir_warrior: {
    id: 'celtic_menhir_warrior',
    variants: {
      splash: require('../../assets/heroes/celtic_menhir_warrior/splash.jpg') as ImageSourcePropType,
      portrait: require('../../assets/heroes/celtic_menhir_warrior/splash.jpg') as ImageSourcePropType,
      card: require('../../assets/heroes/celtic_menhir_warrior/card.png') as ImageSourcePropType,
      detail: require('../../assets/heroes/celtic_menhir_warrior/detail.png') as ImageSourcePropType,
      fullscreen: require('../../assets/heroes/celtic_menhir_warrior/fullscreen.png') as ImageSourcePropType,
      transparent: require('../../assets/heroes/celtic_menhir_warrior/transparent.png') as ImageSourcePropType,
      combat_base: require('../../assets/heroes/celtic_menhir_warrior/combat_base.png') as ImageSourcePropType,
    },
    crop: {
      portraitFocusY: 0.35,
      cardFocusY: 0.35,
      detailFocusY: 0.35,
      sourceAspect: 'portrait',
    },
    viewer: {
      fullscreenVariant: 'fullscreen',
      fullscreenOrientation: 'portrait',
      useContain: true,
      allowDestructiveCrop: false,
    },
    battle: {
      defaultState: 'idle',
      useStateSprites: true,
      useRuntimeSheets: true,
      removeDefaultGlow: true,
      useLegacyDefaultMotion: false,
      runtimeRenderScale: 1.0,
    },
    ui: {
      home: { variant: 'transparent', resizeMode: 'contain', focusY: 0.5, scale: 1.0 },
      card: { variant: 'card', resizeMode: 'contain', focusY: 0.5, scale: 1.0 },
      detailIcon: { variant: 'detail', resizeMode: 'contain', focusY: 0.5, scale: 1.0 },
      selectedPreview: { variant: 'portrait', resizeMode: 'contain', focusY: 0.5, scale: 1.0 },
      fullscreen: { variant: 'fullscreen', resizeMode: 'contain', focusY: 0.5, scale: 1.0, verticalPriority: true },
    },
    runtimeSheets: {
      idle: makeRuntimeSheet(require('../../assets/heroes/celtic_menhir_warrior/runtime/idle_sheet.png') as ImageSourcePropType, 6, 6, 8, true),
      attack: makeRuntimeSheet(require('../../assets/heroes/celtic_menhir_warrior/runtime/attack_sheet.png') as ImageSourcePropType, 5, 5, 12, false),
      skill: makeRuntimeSheet(require('../../assets/heroes/celtic_menhir_warrior/runtime/skill_sheet.png') as ImageSourcePropType, 6, 6, 12, false),
      hit: makeRuntimeSheet(require('../../assets/heroes/celtic_menhir_warrior/runtime/hit_sheet.png') as ImageSourcePropType, 5, 5, 10, false),
      death: makeRuntimeSheet(require('../../assets/heroes/celtic_menhir_warrior/runtime/death_sheet.png') as ImageSourcePropType, 6, 6, 8, false),
    },
  },
  egyptian_oasis_markswoman: {
    id: 'egyptian_oasis_markswoman',
    variants: {
      splash: require('../../assets/heroes/egyptian_oasis_markswoman/splash.jpg') as ImageSourcePropType,
      portrait: require('../../assets/heroes/egyptian_oasis_markswoman/splash.jpg') as ImageSourcePropType,
      card: require('../../assets/heroes/egyptian_oasis_markswoman/card.png') as ImageSourcePropType,
      detail: require('../../assets/heroes/egyptian_oasis_markswoman/detail.png') as ImageSourcePropType,
      fullscreen: require('../../assets/heroes/egyptian_oasis_markswoman/fullscreen.png') as ImageSourcePropType,
      transparent: require('../../assets/heroes/egyptian_oasis_markswoman/transparent.png') as ImageSourcePropType,
      combat_base: require('../../assets/heroes/egyptian_oasis_markswoman/combat_base.png') as ImageSourcePropType,
    },
    crop: {
      portraitFocusY: 0.35,
      cardFocusY: 0.35,
      detailFocusY: 0.35,
      sourceAspect: 'portrait',
    },
    viewer: {
      fullscreenVariant: 'fullscreen',
      fullscreenOrientation: 'portrait',
      useContain: true,
      allowDestructiveCrop: false,
    },
    battle: {
      defaultState: 'idle',
      useStateSprites: true,
      useRuntimeSheets: true,
      removeDefaultGlow: true,
      useLegacyDefaultMotion: false,
      runtimeRenderScale: 1.0,
    },
    ui: {
      home: { variant: 'transparent', resizeMode: 'contain', focusY: 0.5, scale: 1.0 },
      card: { variant: 'card', resizeMode: 'contain', focusY: 0.5, scale: 1.0 },
      detailIcon: { variant: 'detail', resizeMode: 'contain', focusY: 0.5, scale: 1.0 },
      selectedPreview: { variant: 'portrait', resizeMode: 'contain', focusY: 0.5, scale: 1.0 },
      fullscreen: { variant: 'fullscreen', resizeMode: 'contain', focusY: 0.5, scale: 1.0, verticalPriority: true },
    },
    runtimeSheets: {
      idle: makeRuntimeSheet(require('../../assets/heroes/egyptian_oasis_markswoman/runtime/idle_sheet.png') as ImageSourcePropType, 6, 6, 8, true),
      attack: makeRuntimeSheet(require('../../assets/heroes/egyptian_oasis_markswoman/runtime/attack_sheet.png') as ImageSourcePropType, 5, 5, 12, false),
      skill: makeRuntimeSheet(require('../../assets/heroes/egyptian_oasis_markswoman/runtime/skill_sheet.png') as ImageSourcePropType, 6, 6, 12, false),
      hit: makeRuntimeSheet(require('../../assets/heroes/egyptian_oasis_markswoman/runtime/hit_sheet.png') as ImageSourcePropType, 5, 5, 10, false),
      death: makeRuntimeSheet(require('../../assets/heroes/egyptian_oasis_markswoman/runtime/death_sheet.png') as ImageSourcePropType, 6, 6, 8, false),
    },
  },
  yokai_huntress: {
    id: 'yokai_huntress',
    variants: {
      splash: require('../../assets/heroes/yokai_huntress/splash.jpg') as ImageSourcePropType,
      portrait: require('../../assets/heroes/yokai_huntress/splash.jpg') as ImageSourcePropType,
      card: require('../../assets/heroes/yokai_huntress/card.png') as ImageSourcePropType,
      detail: require('../../assets/heroes/yokai_huntress/detail.png') as ImageSourcePropType,
      fullscreen: require('../../assets/heroes/yokai_huntress/fullscreen.png') as ImageSourcePropType,
      transparent: require('../../assets/heroes/yokai_huntress/transparent.png') as ImageSourcePropType,
      combat_base: require('../../assets/heroes/yokai_huntress/combat_base.png') as ImageSourcePropType,
    },
    crop: {
      portraitFocusY: 0.35,
      cardFocusY: 0.35,
      detailFocusY: 0.35,
      sourceAspect: 'portrait',
    },
    viewer: {
      fullscreenVariant: 'fullscreen',
      fullscreenOrientation: 'portrait',
      useContain: true,
      allowDestructiveCrop: false,
    },
    battle: {
      defaultState: 'idle',
      useStateSprites: true,
      useRuntimeSheets: true,
      removeDefaultGlow: true,
      useLegacyDefaultMotion: false,
      runtimeRenderScale: 1.0,
    },
    ui: {
      home: { variant: 'transparent', resizeMode: 'contain', focusY: 0.5, scale: 1.0 },
      card: { variant: 'card', resizeMode: 'contain', focusY: 0.5, scale: 1.0 },
      detailIcon: { variant: 'detail', resizeMode: 'contain', focusY: 0.5, scale: 1.0 },
      selectedPreview: { variant: 'portrait', resizeMode: 'contain', focusY: 0.5, scale: 1.0 },
      fullscreen: { variant: 'fullscreen', resizeMode: 'contain', focusY: 0.5, scale: 1.0, verticalPriority: true },
    },
    runtimeSheets: {
      idle: makeRuntimeSheet(require('../../assets/heroes/yokai_huntress/runtime/idle_sheet.png') as ImageSourcePropType, 6, 6, 8, true),
      attack: makeRuntimeSheet(require('../../assets/heroes/yokai_huntress/runtime/attack_sheet.png') as ImageSourcePropType, 5, 5, 12, false),
      skill: makeRuntimeSheet(require('../../assets/heroes/yokai_huntress/runtime/skill_sheet.png') as ImageSourcePropType, 6, 6, 12, false),
      hit: makeRuntimeSheet(require('../../assets/heroes/yokai_huntress/runtime/hit_sheet.png') as ImageSourcePropType, 5, 5, 10, false),
      death: makeRuntimeSheet(require('../../assets/heroes/yokai_huntress/runtime/death_sheet.png') as ImageSourcePropType, 6, 6, 8, false),
    },
  },
  yokai_thunder_novice: {
    id: 'yokai_thunder_novice',
    variants: {
      splash: require('../../assets/heroes/yokai_thunder_novice/splash.jpg') as ImageSourcePropType,
      portrait: require('../../assets/heroes/yokai_thunder_novice/splash.jpg') as ImageSourcePropType,
      card: require('../../assets/heroes/yokai_thunder_novice/card.png') as ImageSourcePropType,
      detail: require('../../assets/heroes/yokai_thunder_novice/detail.png') as ImageSourcePropType,
      fullscreen: require('../../assets/heroes/yokai_thunder_novice/fullscreen.png') as ImageSourcePropType,
      transparent: require('../../assets/heroes/yokai_thunder_novice/transparent.png') as ImageSourcePropType,
      combat_base: require('../../assets/heroes/yokai_thunder_novice/combat_base.png') as ImageSourcePropType,
    },
    crop: {
      portraitFocusY: 0.35,
      cardFocusY: 0.35,
      detailFocusY: 0.35,
      sourceAspect: 'portrait',
    },
    viewer: {
      fullscreenVariant: 'fullscreen',
      fullscreenOrientation: 'portrait',
      useContain: true,
      allowDestructiveCrop: false,
    },
    battle: {
      defaultState: 'idle',
      useStateSprites: true,
      useRuntimeSheets: true,
      removeDefaultGlow: true,
      useLegacyDefaultMotion: false,
      runtimeRenderScale: 1.0,
    },
    ui: {
      home: { variant: 'transparent', resizeMode: 'contain', focusY: 0.5, scale: 1.0 },
      card: { variant: 'card', resizeMode: 'contain', focusY: 0.5, scale: 1.0 },
      detailIcon: { variant: 'detail', resizeMode: 'contain', focusY: 0.5, scale: 1.0 },
      selectedPreview: { variant: 'portrait', resizeMode: 'contain', focusY: 0.5, scale: 1.0 },
      fullscreen: { variant: 'fullscreen', resizeMode: 'contain', focusY: 0.5, scale: 1.0, verticalPriority: true },
    },
    runtimeSheets: {
      idle: makeRuntimeSheet(require('../../assets/heroes/yokai_thunder_novice/runtime/idle_sheet.png') as ImageSourcePropType, 6, 6, 8, true),
      attack: makeRuntimeSheet(require('../../assets/heroes/yokai_thunder_novice/runtime/attack_sheet.png') as ImageSourcePropType, 5, 5, 12, false),
      skill: makeRuntimeSheet(require('../../assets/heroes/yokai_thunder_novice/runtime/skill_sheet.png') as ImageSourcePropType, 6, 6, 12, false),
      hit: makeRuntimeSheet(require('../../assets/heroes/yokai_thunder_novice/runtime/hit_sheet.png') as ImageSourcePropType, 5, 5, 10, false),
      death: makeRuntimeSheet(require('../../assets/heroes/yokai_thunder_novice/runtime/death_sheet.png') as ImageSourcePropType, 6, 6, 8, false),
    },
  },
  yokai_shinobi_shadow: {
    id: 'yokai_shinobi_shadow',
    variants: {
      splash: require('../../assets/heroes/yokai_shinobi_shadow/splash.jpg') as ImageSourcePropType,
      portrait: require('../../assets/heroes/yokai_shinobi_shadow/splash.jpg') as ImageSourcePropType,
      card: require('../../assets/heroes/yokai_shinobi_shadow/card.png') as ImageSourcePropType,
      detail: require('../../assets/heroes/yokai_shinobi_shadow/detail.png') as ImageSourcePropType,
      fullscreen: require('../../assets/heroes/yokai_shinobi_shadow/fullscreen.png') as ImageSourcePropType,
      transparent: require('../../assets/heroes/yokai_shinobi_shadow/transparent.png') as ImageSourcePropType,
      combat_base: require('../../assets/heroes/yokai_shinobi_shadow/combat_base.png') as ImageSourcePropType,
    },
    crop: {
      portraitFocusY: 0.35,
      cardFocusY: 0.35,
      detailFocusY: 0.35,
      sourceAspect: 'portrait',
    },
    viewer: {
      fullscreenVariant: 'fullscreen',
      fullscreenOrientation: 'portrait',
      useContain: true,
      allowDestructiveCrop: false,
    },
    battle: {
      defaultState: 'idle',
      useStateSprites: true,
      useRuntimeSheets: true,
      removeDefaultGlow: true,
      useLegacyDefaultMotion: false,
      runtimeRenderScale: 1.0,
    },
    ui: {
      home: { variant: 'transparent', resizeMode: 'contain', focusY: 0.5, scale: 1.0 },
      card: { variant: 'card', resizeMode: 'contain', focusY: 0.5, scale: 1.0 },
      detailIcon: { variant: 'detail', resizeMode: 'contain', focusY: 0.5, scale: 1.0 },
      selectedPreview: { variant: 'portrait', resizeMode: 'contain', focusY: 0.5, scale: 1.0 },
      fullscreen: { variant: 'fullscreen', resizeMode: 'contain', focusY: 0.5, scale: 1.0, verticalPriority: true },
    },
    runtimeSheets: {
      idle: makeRuntimeSheet(require('../../assets/heroes/yokai_shinobi_shadow/runtime/idle_sheet.png') as ImageSourcePropType, 6, 6, 8, true),
      attack: makeRuntimeSheet(require('../../assets/heroes/yokai_shinobi_shadow/runtime/attack_sheet.png') as ImageSourcePropType, 5, 5, 12, false),
      skill: makeRuntimeSheet(require('../../assets/heroes/yokai_shinobi_shadow/runtime/skill_sheet.png') as ImageSourcePropType, 6, 6, 12, false),
      hit: makeRuntimeSheet(require('../../assets/heroes/yokai_shinobi_shadow/runtime/hit_sheet.png') as ImageSourcePropType, 5, 5, 10, false),
      death: makeRuntimeSheet(require('../../assets/heroes/yokai_shinobi_shadow/runtime/death_sheet.png') as ImageSourcePropType, 6, 6, 8, false),
    },
  },
  angelic_cantor: {
    id: 'angelic_cantor',
    variants: {
      splash: require('../../assets/heroes/angelic_cantor/splash.jpg') as ImageSourcePropType,
      portrait: require('../../assets/heroes/angelic_cantor/splash.jpg') as ImageSourcePropType,
      card: require('../../assets/heroes/angelic_cantor/card.png') as ImageSourcePropType,
      detail: require('../../assets/heroes/angelic_cantor/detail.png') as ImageSourcePropType,
      fullscreen: require('../../assets/heroes/angelic_cantor/fullscreen.png') as ImageSourcePropType,
      transparent: require('../../assets/heroes/angelic_cantor/transparent.png') as ImageSourcePropType,
      combat_base: require('../../assets/heroes/angelic_cantor/combat_base.png') as ImageSourcePropType,
    },
    crop: {
      portraitFocusY: 0.35,
      cardFocusY: 0.35,
      detailFocusY: 0.35,
      sourceAspect: 'portrait',
    },
    viewer: {
      fullscreenVariant: 'fullscreen',
      fullscreenOrientation: 'portrait',
      useContain: true,
      allowDestructiveCrop: false,
    },
    battle: {
      defaultState: 'idle',
      useStateSprites: true,
      useRuntimeSheets: true,
      removeDefaultGlow: true,
      useLegacyDefaultMotion: false,
      runtimeRenderScale: 1.0,
    },
    ui: {
      home: { variant: 'transparent', resizeMode: 'contain', focusY: 0.5, scale: 1.0 },
      card: { variant: 'card', resizeMode: 'contain', focusY: 0.5, scale: 1.0 },
      detailIcon: { variant: 'detail', resizeMode: 'contain', focusY: 0.5, scale: 1.0 },
      selectedPreview: { variant: 'portrait', resizeMode: 'contain', focusY: 0.5, scale: 1.0 },
      fullscreen: { variant: 'fullscreen', resizeMode: 'contain', focusY: 0.5, scale: 1.0, verticalPriority: true },
    },
    runtimeSheets: {
      idle: makeRuntimeSheet(require('../../assets/heroes/angelic_cantor/runtime/idle_sheet.png') as ImageSourcePropType, 6, 6, 8, true),
      attack: makeRuntimeSheet(require('../../assets/heroes/angelic_cantor/runtime/attack_sheet.png') as ImageSourcePropType, 5, 5, 12, false),
      skill: makeRuntimeSheet(require('../../assets/heroes/angelic_cantor/runtime/skill_sheet.png') as ImageSourcePropType, 6, 6, 12, false),
      hit: makeRuntimeSheet(require('../../assets/heroes/angelic_cantor/runtime/hit_sheet.png') as ImageSourcePropType, 5, 5, 10, false),
      death: makeRuntimeSheet(require('../../assets/heroes/angelic_cantor/runtime/death_sheet.png') as ImageSourcePropType, 6, 6, 8, false),
    },
  },
  egyptian_nile_healer: {
    id: 'egyptian_nile_healer',
    variants: {
      splash: require('../../assets/heroes/egyptian_nile_healer/splash.jpg') as ImageSourcePropType,
      portrait: require('../../assets/heroes/egyptian_nile_healer/splash.jpg') as ImageSourcePropType,
      card: require('../../assets/heroes/egyptian_nile_healer/card.png') as ImageSourcePropType,
      detail: require('../../assets/heroes/egyptian_nile_healer/detail.png') as ImageSourcePropType,
      fullscreen: require('../../assets/heroes/egyptian_nile_healer/fullscreen.png') as ImageSourcePropType,
      transparent: require('../../assets/heroes/egyptian_nile_healer/transparent.png') as ImageSourcePropType,
      combat_base: require('../../assets/heroes/egyptian_nile_healer/combat_base.png') as ImageSourcePropType,
    },
    crop: {
      portraitFocusY: 0.35,
      cardFocusY: 0.35,
      detailFocusY: 0.35,
      sourceAspect: 'portrait',
    },
    viewer: {
      fullscreenVariant: 'fullscreen',
      fullscreenOrientation: 'portrait',
      useContain: true,
      allowDestructiveCrop: false,
    },
    battle: {
      defaultState: 'idle',
      useStateSprites: true,
      useRuntimeSheets: true,
      removeDefaultGlow: true,
      useLegacyDefaultMotion: false,
      runtimeRenderScale: 1.0,
    },
    ui: {
      home: { variant: 'transparent', resizeMode: 'contain', focusY: 0.5, scale: 1.0 },
      card: { variant: 'card', resizeMode: 'contain', focusY: 0.5, scale: 1.0 },
      detailIcon: { variant: 'detail', resizeMode: 'contain', focusY: 0.5, scale: 1.0 },
      selectedPreview: { variant: 'portrait', resizeMode: 'contain', focusY: 0.5, scale: 1.0 },
      fullscreen: { variant: 'fullscreen', resizeMode: 'contain', focusY: 0.5, scale: 1.0, verticalPriority: true },
    },
    runtimeSheets: {
      idle: makeRuntimeSheet(require('../../assets/heroes/egyptian_nile_healer/runtime/idle_sheet.png') as ImageSourcePropType, 6, 6, 8, true),
      attack: makeRuntimeSheet(require('../../assets/heroes/egyptian_nile_healer/runtime/attack_sheet.png') as ImageSourcePropType, 5, 5, 12, false),
      skill: makeRuntimeSheet(require('../../assets/heroes/egyptian_nile_healer/runtime/skill_sheet.png') as ImageSourcePropType, 6, 6, 12, false),
      hit: makeRuntimeSheet(require('../../assets/heroes/egyptian_nile_healer/runtime/hit_sheet.png') as ImageSourcePropType, 5, 5, 10, false),
      death: makeRuntimeSheet(require('../../assets/heroes/egyptian_nile_healer/runtime/death_sheet.png') as ImageSourcePropType, 6, 6, 8, false),
    },
  },
  cursed_bone_sibyl: {
    id: 'cursed_bone_sibyl',
    variants: {
      splash: require('../../assets/heroes/cursed_bone_sibyl/splash.jpg') as ImageSourcePropType,
      portrait: require('../../assets/heroes/cursed_bone_sibyl/splash.jpg') as ImageSourcePropType,
      card: require('../../assets/heroes/cursed_bone_sibyl/card.png') as ImageSourcePropType,
      detail: require('../../assets/heroes/cursed_bone_sibyl/detail.png') as ImageSourcePropType,
      fullscreen: require('../../assets/heroes/cursed_bone_sibyl/fullscreen.png') as ImageSourcePropType,
      transparent: require('../../assets/heroes/cursed_bone_sibyl/transparent.png') as ImageSourcePropType,
      combat_base: require('../../assets/heroes/cursed_bone_sibyl/combat_base.png') as ImageSourcePropType,
    },
    crop: {
      portraitFocusY: 0.35,
      cardFocusY: 0.35,
      detailFocusY: 0.35,
      sourceAspect: 'portrait',
    },
    viewer: {
      fullscreenVariant: 'fullscreen',
      fullscreenOrientation: 'portrait',
      useContain: true,
      allowDestructiveCrop: false,
    },
    battle: {
      defaultState: 'idle',
      useStateSprites: true,
      useRuntimeSheets: true,
      removeDefaultGlow: true,
      useLegacyDefaultMotion: false,
      runtimeRenderScale: 1.0,
    },
    ui: {
      home: { variant: 'transparent', resizeMode: 'contain', focusY: 0.5, scale: 1.0 },
      card: { variant: 'card', resizeMode: 'contain', focusY: 0.5, scale: 1.0 },
      detailIcon: { variant: 'detail', resizeMode: 'contain', focusY: 0.5, scale: 1.0 },
      selectedPreview: { variant: 'portrait', resizeMode: 'contain', focusY: 0.5, scale: 1.0 },
      fullscreen: { variant: 'fullscreen', resizeMode: 'contain', focusY: 0.5, scale: 1.0, verticalPriority: true },
    },
    runtimeSheets: {
      idle: makeRuntimeSheet(require('../../assets/heroes/cursed_bone_sibyl/runtime/idle_sheet.png') as ImageSourcePropType, 6, 6, 8, true),
      attack: makeRuntimeSheet(require('../../assets/heroes/cursed_bone_sibyl/runtime/attack_sheet.png') as ImageSourcePropType, 5, 5, 12, false),
      skill: makeRuntimeSheet(require('../../assets/heroes/cursed_bone_sibyl/runtime/skill_sheet.png') as ImageSourcePropType, 6, 6, 12, false),
      hit: makeRuntimeSheet(require('../../assets/heroes/cursed_bone_sibyl/runtime/hit_sheet.png') as ImageSourcePropType, 5, 5, 10, false),
      death: makeRuntimeSheet(require('../../assets/heroes/cursed_bone_sibyl/runtime/death_sheet.png') as ImageSourcePropType, 6, 6, 8, false),
    },
  },
  demonic_infernal_adept: {
    id: 'demonic_infernal_adept',
    variants: {
      splash: require('../../assets/heroes/demonic_infernal_adept/splash.jpg') as ImageSourcePropType,
      portrait: require('../../assets/heroes/demonic_infernal_adept/splash.jpg') as ImageSourcePropType,
      card: require('../../assets/heroes/demonic_infernal_adept/card.png') as ImageSourcePropType,
      detail: require('../../assets/heroes/demonic_infernal_adept/detail.png') as ImageSourcePropType,
      fullscreen: require('../../assets/heroes/demonic_infernal_adept/fullscreen.png') as ImageSourcePropType,
      transparent: require('../../assets/heroes/demonic_infernal_adept/transparent.png') as ImageSourcePropType,
      combat_base: require('../../assets/heroes/demonic_infernal_adept/combat_base.png') as ImageSourcePropType,
    },
    crop: {
      portraitFocusY: 0.35,
      cardFocusY: 0.35,
      detailFocusY: 0.35,
      sourceAspect: 'portrait',
    },
    viewer: {
      fullscreenVariant: 'fullscreen',
      fullscreenOrientation: 'portrait',
      useContain: true,
      allowDestructiveCrop: false,
    },
    battle: {
      defaultState: 'idle',
      useStateSprites: true,
      useRuntimeSheets: true,
      removeDefaultGlow: true,
      useLegacyDefaultMotion: false,
      runtimeRenderScale: 1.0,
    },
    ui: {
      home: { variant: 'transparent', resizeMode: 'contain', focusY: 0.5, scale: 1.0 },
      card: { variant: 'card', resizeMode: 'contain', focusY: 0.5, scale: 1.0 },
      detailIcon: { variant: 'detail', resizeMode: 'contain', focusY: 0.5, scale: 1.0 },
      selectedPreview: { variant: 'portrait', resizeMode: 'contain', focusY: 0.5, scale: 1.0 },
      fullscreen: { variant: 'fullscreen', resizeMode: 'contain', focusY: 0.5, scale: 1.0, verticalPriority: true },
    },
    runtimeSheets: {
      idle: makeRuntimeSheet(require('../../assets/heroes/demonic_infernal_adept/runtime/idle_sheet.png') as ImageSourcePropType, 6, 6, 8, true),
      attack: makeRuntimeSheet(require('../../assets/heroes/demonic_infernal_adept/runtime/attack_sheet.png') as ImageSourcePropType, 5, 5, 12, false),
      skill: makeRuntimeSheet(require('../../assets/heroes/demonic_infernal_adept/runtime/skill_sheet.png') as ImageSourcePropType, 6, 6, 12, false),
      hit: makeRuntimeSheet(require('../../assets/heroes/demonic_infernal_adept/runtime/hit_sheet.png') as ImageSourcePropType, 5, 5, 10, false),
      death: makeRuntimeSheet(require('../../assets/heroes/demonic_infernal_adept/runtime/death_sheet.png') as ImageSourcePropType, 6, 6, 8, false),
    },
  },
};

export function isPlaceholderHero1Star2Star(heroId?: string | null): boolean {
  return !!heroId && Object.prototype.hasOwnProperty.call(
    PLACEHOLDER_HERO_CONTRACTS_1STAR_2STAR,
    String(heroId).toLowerCase(),
  );
}
